language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: AAlNPBuxRNT3Ov5juvl8GN2psm21KDAadptLrJRlkoiBJJabxU2ofrkwo+RI31LGS3GNS+x85i2/02GxpZatDRTwYj6f0QN8r2GtEMIt4J2420mwCVgVwSv1jN+tkp8vBzdbEULAFYY0gNV+WEOyZl75jNf+pFX6BDnQsXmIXsM=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: EevhNDp+BXan47xHgFdbEqwly3Kj2o8NmJvbLEQQYNNOTOzhNdE8roxcEm/iK4VpHBb0kYL0TrrEXpeGo5WJip/vWa+fFjkYX4kZSa36j+CK7bldl4Nxv1RBEtIU+lwrvnaodUh9sbZmeLrkzsp+0hFq5SGWQCbuYPkIGYRz2KM=
sudo: false
